/*
 * Store Information
 * ### Store Information Reference The Store Information object, and Get Store Information endpoint, manage store profile settings. A Store Information object represents an individual store’s profile and metadata.  ### System Reference The Get a Timestamp endpoint generates a timestamp ping to check the system status.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.21
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StoreInformation);
  }
}(this, function(expect, StoreInformation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DateFormat', function() {
      beforeEach(function() {
        instance = new StoreInformation.DateFormat();
      });

      it('should create an instance of DateFormat', function() {
        expect(instance).to.be.a(StoreInformation.DateFormat);
      });

      it('should have the property display (base name: "display")', function() {
        expect(instance).to.have.property('display');
        // expect(instance.display).to.be(expectedValueLiteral);
      });

      it('should have the property export (base name: "export")', function() {
        expect(instance).to.have.property('export');
        // expect(instance.export).to.be(expectedValueLiteral);
      });

      it('should have the property extended_display (base name: "extended_display")', function() {
        expect(instance).to.have.property('extended_display');
        // expect(instance.extended_display).to.be(expectedValueLiteral);
      });

    });
  });

}));
