/**
 * Wishlist
 * ## Wishlist API    The Wishlist API allows a developer to create and manage customer [Wishlists](https://support.bigcommerce.com/s/article/Wishlists). A Wishlist allows you to see what your customers are interested in and saving on the store. With this information you’ll be able to create targeted campaigns to help merchants grow their business. Customer API OAuth scopes give you access to Wishlists API. See [OAuth Scopes](https://developer.bigcommerce.com/api-docs/getting-started/authentication#authentication_oauth-scopes).
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Error from '../model/Error';
import InlineResponse201 from '../model/InlineResponse201';
import WishlistItemPost1 from '../model/WishlistItemPost1';

/**
* WishlistsItems service.
* @module api/WishlistsItemsApi
* @version 3.0
*/
export default class WishlistsItemsApi {

    /**
    * Constructs a new WishlistsItemsApi. 
    * @alias module:api/WishlistsItemsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the wishlistsItemsByIdDelete operation.
     * @callback module:api/WishlistsItemsApi~wishlistsItemsByIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse201} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Wishlist Item
     * Deletes a Wishlist Item.
     * @param {Object} opts Optional parameters
     * @param {module:api/WishlistsItemsApi~wishlistsItemsByIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse201}
     */
    wishlistsItemsByIdDelete(wishlistId, itemId, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'wishlist_id': wishlistId,
        'item_id': itemId
      };
      let queryParams = {
      };
      let headerParams = {
        'Accept': opts['accept'],
        'Content-Type': opts['contentType']
      };
      let formParams = {
      };

      let authNames = ['X-Auth-Client', 'X-Auth-Token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse201;

      return this.apiClient.callApi(
        '/wishlists/{wishlist_id}/items/{item_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the wishlistsItemsByIdPost operation.
     * @callback module:api/WishlistsItemsApi~wishlistsItemsByIdPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse201} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Wishlist Item
     * Adds a Wishlist Item. More than one item can be added at a time.
     * @param {Object} opts Optional parameters
     * @param {module:api/WishlistsItemsApi~wishlistsItemsByIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse201}
     */
    wishlistsItemsByIdPost(wishlistId, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        'wishlist_id': wishlistId
      };
      let queryParams = {
      };
      let headerParams = {
        'Accept': opts['accept'],
        'Content-Type': opts['contentType']
      };
      let formParams = {
      };

      let authNames = ['X-Auth-Client', 'X-Auth-Token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse201;

      return this.apiClient.callApi(
        '/wishlists/{wishlist_id}/items', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
