/**
 * Carts
 * ### Cart Allows for a cart to be created using BigCommerce cart logic. The existing BigCommerce front end cart can be bypassed.  Notes: - A **cart** `id` is the same as a **checkout** `id`. - A cart can be created by adding an existing **catalog item** or a **custom item**. - Carts are valid for 30 days from the last modification. This can include creating the cart or editing the cart. - Redirect URLs can be generated only from carts created using the Server to Server Cart API. To restore a cart that was created on the storefront, either by a shopper or the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import InlineResponse201 from '../model/InlineResponse201';

/**
* CartRedirectURLs service.
* @module api/CartRedirectURLsApi
* @version 3.0
*/
export default class CartRedirectURLsApi {

    /**
    * Constructs a new CartRedirectURLsApi. 
    * @alias module:api/CartRedirectURLsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createCartRedirectURL operation.
     * @callback module:api/CartRedirectURLsApi~createCartRedirectURLCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse201} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Cart Redirect URL
     * Creates a **Cart** redirect URL for redirecting a shopper to an already created cart using the &#x60;cartId&#x60;.  **Usage Notes**  * Redirect URLs can also be created via **Create a Cart** requests by appending &#x60;include&#x3D;redirect_urls&#x60;. * A **Carts** redirect URLs may only be used once.  * Once a redirect URL has been visited, it will be invalidated and cannot be used again.  * If your application requires URLs to be visited more than once, consider generating a fresh one each time you need to restore a cart, and redirecting to the URL from your own application. * Redirect URLs can be generated only from carts created using the Server to Server Cart API.  * To restore a cart that was created on the storefront, either by a shopper or the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
     * @param {module:api/CartRedirectURLsApi~createCartRedirectURLCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse201}
     */
    createCartRedirectURL(cartId, accept, contentType, callback) {
      let postBody = null;

      let pathParams = {
        'cartId': cartId
      };
      let queryParams = {
      };
      let headerParams = {
        'Accept': accept,
        'Content-Type': contentType
      };
      let formParams = {
      };

      let authNames = ['X-Auth-Client', 'X-Auth-Token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse201;

      return this.apiClient.callApi(
        '/carts/{cartId}/redirect_urls', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
