/**
 * Widgets
 * Widgets API allows developers to programatically inject content into a BigCommerce theme. To learn how to use Widgets, see our [Widgets Overview](/api-docs/storefront/widgets/widgets-overview).
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pagination1 from './Pagination1';

/**
* The MetaCollection1 model module.
* @module model/MetaCollection1
* @version 3.0
*/
export default class MetaCollection1 {
    /**
    * Constructs a new <code>MetaCollection1</code>.
    * Data about the response, including pagination and collection totals.
    * @alias module:model/MetaCollection1
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MetaCollection1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MetaCollection1} obj Optional instance to populate.
    * @return {module:model/MetaCollection1} The populated <code>MetaCollection1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaCollection1();
                        
            
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination1.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Pagination1} pagination
    */
    'pagination' = undefined;




}
