/**
 * Widgets
 * Widgets API allows developers to programatically inject content into a BigCommerce theme. To learn how to use Widgets, see our [Widgets Overview](/api-docs/storefront/widgets/widgets-overview).
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The NewmodelInner model module.
* @module model/NewmodelInner
* @version 3.0
*/
export default class NewmodelInner {
    /**
    * Constructs a new <code>NewmodelInner</code>.
    * @alias module:model/NewmodelInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NewmodelInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NewmodelInner} obj Optional instance to populate.
    * @return {module:model/NewmodelInner} The populated <code>NewmodelInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewmodelInner();
                        
            
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Number');
            }
            if (data.hasOwnProperty('typeMeta')) {
                obj['typeMeta'] = ApiClient.convertToType(data['typeMeta'], 'String');
            }
            if (data.hasOwnProperty('conditional')) {
                obj['conditional'] = ApiClient.convertToType(data['conditional'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} type
    */
    'type' = undefined;
    /**
    * @member {String} label
    */
    'label' = undefined;
    /**
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {Number} default
    */
    'default' = undefined;
    /**
    * @member {String} typeMeta
    */
    'typeMeta' = undefined;
    /**
    * @member {String} conditional
    */
    'conditional' = undefined;




}
