/**
 * Data Model for BigCommerce's v3 Server-to-Server Cart API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/AppliedCoupon', 'Model/AppliedDiscount', 'Model/ProductOption'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AppliedCoupon'), require('./AppliedDiscount'), require('./ProductOption'));
  } else {
    // Browser globals (root is window)
    if (!root.DataModelForBigCommercesV3ServerToServerCartApi) {
      root.DataModelForBigCommercesV3ServerToServerCartApi = {};
    }
    root.DataModelForBigCommercesV3ServerToServerCartApi.BaseItem = factory(root.DataModelForBigCommercesV3ServerToServerCartApi.ApiClient, root.DataModelForBigCommercesV3ServerToServerCartApi.AppliedCoupon, root.DataModelForBigCommercesV3ServerToServerCartApi.AppliedDiscount, root.DataModelForBigCommercesV3ServerToServerCartApi.ProductOption);
  }
}(this, function(ApiClient, AppliedCoupon, AppliedDiscount, ProductOption) {
  'use strict';




  /**
   * The BaseItem model module.
   * @module Model/BaseItem
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>BaseItem</code>.
   * @alias module:Model/BaseItem
   * @class
   * @param quantity {Number} 
   */
  var exports = function(quantity) {
    var _this = this;








    _this['quantity'] = quantity;











  };

  /**
   * Constructs a <code>BaseItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/BaseItem} obj Optional instance to populate.
   * @return {module:Model/BaseItem} The populated <code>BaseItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('parent_id')) {
        obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'String');
      }
      if (data.hasOwnProperty('variant_id')) {
        obj['variant_id'] = ApiClient.convertToType(data['variant_id'], 'Number');
      }
      if (data.hasOwnProperty('product_id')) {
        obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('quantity')) {
        obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
      }
      if (data.hasOwnProperty('is_taxable')) {
        obj['is_taxable'] = ApiClient.convertToType(data['is_taxable'], 'Boolean');
      }
      if (data.hasOwnProperty('image_url')) {
        obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
      }
      if (data.hasOwnProperty('discounts')) {
        obj['discounts'] = ApiClient.convertToType(data['discounts'], [AppliedDiscount]);
      }
      if (data.hasOwnProperty('coupons')) {
        obj['coupons'] = ApiClient.convertToType(data['coupons'], [AppliedCoupon]);
      }
      if (data.hasOwnProperty('discount_amount')) {
        obj['discount_amount'] = ApiClient.convertToType(data['discount_amount'], 'Number');
      }
      if (data.hasOwnProperty('coupon_amount')) {
        obj['coupon_amount'] = ApiClient.convertToType(data['coupon_amount'], 'Number');
      }
      if (data.hasOwnProperty('list_price')) {
        obj['list_price'] = ApiClient.convertToType(data['list_price'], 'Number');
      }
      if (data.hasOwnProperty('sale_price')) {
        obj['sale_price'] = ApiClient.convertToType(data['sale_price'], 'Number');
      }
      if (data.hasOwnProperty('extended_list_price')) {
        obj['extended_list_price'] = ApiClient.convertToType(data['extended_list_price'], 'Number');
      }
      if (data.hasOwnProperty('extended_sale_price')) {
        obj['extended_sale_price'] = ApiClient.convertToType(data['extended_sale_price'], 'Number');
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = ApiClient.convertToType(data['options'], [ProductOption]);
      }
    }
    return obj;
  }

  /**
   * The line-item ID.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The parent line-item ID.
   * @member {String} parent_id
   */
  exports.prototype['parent_id'] = undefined;
  /**
   * @member {Number} variant_id
   */
  exports.prototype['variant_id'] = undefined;
  /**
   * @member {Number} product_id
   */
  exports.prototype['product_id'] = undefined;
  /**
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * The item's product name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The product URL.
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {Number} quantity
   */
  exports.prototype['quantity'] = undefined;
  /**
   * @member {Boolean} is_taxable
   */
  exports.prototype['is_taxable'] = undefined;
  /**
   * @member {String} image_url
   */
  exports.prototype['image_url'] = undefined;
  /**
   * @member {Array.<module:Model/AppliedDiscount>} discounts
   */
  exports.prototype['discounts'] = undefined;
  /**
   * @member {Array.<module:Model/AppliedCoupon>} coupons
   */
  exports.prototype['coupons'] = undefined;
  /**
   * The total value of all discounts applied to this item.
   * @member {Number} discount_amount
   */
  exports.prototype['discount_amount'] = undefined;
  /**
   * The total value of all coupons applied to this item.
   * @member {Number} coupon_amount
   */
  exports.prototype['coupon_amount'] = undefined;
  /**
   * Item's list price, as quoted by the manufacturer/distributor.
   * @member {Number} list_price
   */
  exports.prototype['list_price'] = undefined;
  /**
   * Item's price after all discounts are applied. (The final price before tax calculation.)
   * @member {Number} sale_price
   */
  exports.prototype['sale_price'] = undefined;
  /**
   * Item's list price multiplied by the quantity.
   * @member {Number} extended_list_price
   */
  exports.prototype['extended_list_price'] = undefined;
  /**
   * Item's sale price multiplied by the quantity.
   * @member {Number} extended_sale_price
   */
  exports.prototype['extended_sale_price'] = undefined;
  /**
   * The list of selected options for this product.
   * @member {Array.<module:Model/ProductOption>} options
   */
  exports.prototype['options'] = undefined;



  return exports;
}));


