/**
 * BigCommerce Channels API
 * The Channels API enables you to create and manage listings across a BigCommerce merchant's sales channels.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/Channel', 'Model/Meta'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Channel'), require('./Meta'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceChannelsApi) {
      root.BigCommerceChannelsApi = {};
    }
    root.BigCommerceChannelsApi.ChannelResponse = factory(root.BigCommerceChannelsApi.ApiClient, root.BigCommerceChannelsApi.Channel, root.BigCommerceChannelsApi.Meta);
  }
}(this, function(ApiClient, Channel, Meta) {
  'use strict';




  /**
   * The ChannelResponse model module.
   * @module Model/ChannelResponse
   * @version 1.0
   */

  /**
   * Constructs a new <code>ChannelResponse</code>.
   * Response payload for the BigCommerce API. 
   * @alias module:Model/ChannelResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ChannelResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/ChannelResponse} obj Optional instance to populate.
   * @return {module:Model/ChannelResponse} The populated <code>ChannelResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = Channel.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = Meta.constructFromObject(data['meta']);
      }
    }
    return obj;
  }

  /**
   * @member {module:Model/Channel} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:Model/Meta} meta
   */
  exports.prototype['meta'] = undefined;



  return exports;
}));


