/**
 * Store Information APIs
 * The Store Information object, and Get Store Information endpoint, manage store profile settings.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StoreInformationApIs) {
      root.StoreInformationApIs = {};
    }
    root.StoreInformationApIs.DateFormat = factory(root.StoreInformationApIs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DateFormat model module.
   * @module Model/DateFormat
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DateFormat</code>.
   * @alias module:Model/DateFormat
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>DateFormat</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/DateFormat} obj Optional instance to populate.
   * @return {module:Model/DateFormat} The populated <code>DateFormat</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('display')) {
        obj['display'] = ApiClient.convertToType(data['display'], 'String');
      }
      if (data.hasOwnProperty('export')) {
        obj['export'] = ApiClient.convertToType(data['export'], 'String');
      }
      if (data.hasOwnProperty('extended_display')) {
        obj['extended_display'] = ApiClient.convertToType(data['extended_display'], 'String');
      }
    }
    return obj;
  }

  /**
   * string that defines dates’ display format, in the pattern: M jS Y
   * @member {String} display
   */
  exports.prototype['display'] = undefined;
  /**
   * string that defines the CSV export format for orders, customers, and products, in the pattern: M jS Y
   * @member {String} export
   */
  exports.prototype['export'] = undefined;
  /**
   * string that defines dates’ extended-display format, in the pattern: M jS Y @ g:i A.
   * @member {String} extended_display
   */
  exports.prototype['extended_display'] = undefined;



  return exports;
}));


