/**
 * BigCommerce Channels API
 * The Channels API enables you to create and manage listings across a BigCommerce merchant's sales channels.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/CollectionMeta', 'Model/Listing'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CollectionMeta'), require('./Listing'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceChannelsApi) {
      root.BigCommerceChannelsApi = {};
    }
    root.BigCommerceChannelsApi.ListingCollectionResponse = factory(root.BigCommerceChannelsApi.ApiClient, root.BigCommerceChannelsApi.CollectionMeta, root.BigCommerceChannelsApi.Listing);
  }
}(this, function(ApiClient, CollectionMeta, Listing) {
  'use strict';




  /**
   * The ListingCollectionResponse model module.
   * @module Model/ListingCollectionResponse
   * @version 1.0
   */

  /**
   * Constructs a new <code>ListingCollectionResponse</code>.
   * @alias module:Model/ListingCollectionResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ListingCollectionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/ListingCollectionResponse} obj Optional instance to populate.
   * @return {module:Model/ListingCollectionResponse} The populated <code>ListingCollectionResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [Listing]);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = CollectionMeta.constructFromObject(data['meta']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:Model/Listing>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:Model/CollectionMeta} meta
   */
  exports.prototype['meta'] = undefined;



  return exports;
}));


