/**
 * BigCommerce API
 * A Swagger Document for the BigCommmerce v3 Catalog API.
 *
 * OpenAPI spec version: 3.0.0b
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/MetafieldBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MetafieldBase'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceApi) {
      root.BigCommerceApi = {};
    }
    root.BigCommerceApi.MetafieldPost = factory(root.BigCommerceApi.ApiClient, root.BigCommerceApi.MetafieldBase);
  }
}(this, function(ApiClient, MetafieldBase) {
  'use strict';




  /**
   * The MetafieldPost model module.
   * @module Model/MetafieldPost
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>MetafieldPost</code>.
   * The model for a POST to create metafield. 
   * @alias module:Model/MetafieldPost
   * @class
   * @implements module:Model/MetafieldBase
   */
  var exports = function() {
    var _this = this;

    MetafieldBase.call(_this);
  };

  /**
   * Constructs a <code>MetafieldPost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/MetafieldPost} obj Optional instance to populate.
   * @return {module:Model/MetafieldPost} The populated <code>MetafieldPost</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      MetafieldBase.constructFromObject(data, obj);
    }
    return obj;
  }


  // Implement MetafieldBase interface:
  /**
   * Determines whether the field is completely private to the app that owns the field (`app_only`), or visible to other API consumers (`read`), or completely open for reading and writing to other apps (`write`). 
   * @member {String} permission_set
   */
exports.prototype['permission_set'] = undefined;

  /**
   * Namespace for the metafield, for organizational purposes. 
   * @member {String} namespace
   */
exports.prototype['namespace'] = undefined;

  /**
   * The name of the field, for example: `location_id`, `color`. 
   * @member {String} key
   */
exports.prototype['key'] = undefined;

  /**
   * The value of the field, for example: `1`, `blue`. 
   * @member {String} value
   */
exports.prototype['value'] = undefined;

  /**
   * Description for the metafields. 
   * @member {String} description
   */
exports.prototype['description'] = undefined;

  /**
   * The type of resource with which the metafield is associated. 
   * @member {String} resource_type
   */
exports.prototype['resource_type'] = undefined;

  /**
   * The unique identifier for the resource with which the metafield is associated. 
   * @member {Number} resource_id
   */
exports.prototype['resource_id'] = undefined;



  return exports;
}));


