/**
 * BigCommerce API
 * A Swagger Document for the BigCommmerce v3 Catalog API.
 *
 * OpenAPI spec version: 3.0.0b
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/Meta', 'Model/ModifierValue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Meta'), require('./ModifierValue'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceApi) {
      root.BigCommerceApi = {};
    }
    root.BigCommerceApi.ModifierValueResponse = factory(root.BigCommerceApi.ApiClient, root.BigCommerceApi.Meta, root.BigCommerceApi.ModifierValue);
  }
}(this, function(ApiClient, Meta, ModifierValue) {
  'use strict';




  /**
   * The ModifierValueResponse model module.
   * @module Model/ModifierValueResponse
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>ModifierValueResponse</code>.
   * Response payload for the BigCommerce API. 
   * @alias module:Model/ModifierValueResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ModifierValueResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/ModifierValueResponse} obj Optional instance to populate.
   * @return {module:Model/ModifierValueResponse} The populated <code>ModifierValueResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ModifierValue.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = Meta.constructFromObject(data['meta']);
      }
    }
    return obj;
  }

  /**
   * @member {module:Model/ModifierValue} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:Model/Meta} meta
   */
  exports.prototype['meta'] = undefined;



  return exports;
}));


