/**
 * BigCommerce API
 * A Swagger Document for the BigCommmerce v3 Catalog API.
 *
 * OpenAPI spec version: 3.0.0b
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceApi) {
      root.BigCommerceApi = {};
    }
    root.BigCommerceApi.ModifierValueBaseAdjustersPurchasingDisabled = factory(root.BigCommerceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ModifierValueBaseAdjustersPurchasingDisabled model module.
   * @module Model/ModifierValueBaseAdjustersPurchasingDisabled
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>ModifierValueBaseAdjustersPurchasingDisabled</code>.
   * @alias module:Model/ModifierValueBaseAdjustersPurchasingDisabled
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ModifierValueBaseAdjustersPurchasingDisabled</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/ModifierValueBaseAdjustersPurchasingDisabled} obj Optional instance to populate.
   * @return {module:Model/ModifierValueBaseAdjustersPurchasingDisabled} The populated <code>ModifierValueBaseAdjustersPurchasingDisabled</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
    }
    return obj;
  }

  /**
   * Flag for whether the modifier value disables purchasing when selected on the storefront. This can be used for temporarily disabling a particular modifier value. 
   * @member {Boolean} status
   */
  exports.prototype['status'] = undefined;
  /**
   * The message displayed on the storefront when the purchasing disabled status is `true`. 
   * @member {String} message
   */
  exports.prototype['message'] = undefined;



  return exports;
}));


