/**
 * Orders APIs
 * Orders APIs integrate with point-of-sale, shipping, distribution, and inventory-management systems.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OrdersApIs) {
      root.OrdersApIs = {};
    }
    root.OrdersApIs.OrderTax = factory(root.OrdersApIs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OrderTax model module.
   * @module Model/OrderTax
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderTax</code>.
   * @alias module:Model/OrderTax
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>OrderTax</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/OrderTax} obj Optional instance to populate.
   * @return {module:Model/OrderTax} The populated <code>OrderTax</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('order_id')) {
        obj['order_id'] = ApiClient.convertToType(data['order_id'], 'Number');
      }
      if (data.hasOwnProperty('order_address_id')) {
        obj['order_address_id'] = ApiClient.convertToType(data['order_address_id'], 'Number');
      }
      if (data.hasOwnProperty('tax_rate_id')) {
        obj['tax_rate_id'] = ApiClient.convertToType(data['tax_rate_id'], 'Number');
      }
      if (data.hasOwnProperty('tax_class_id')) {
        obj['tax_class_id'] = ApiClient.convertToType(data['tax_class_id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('class')) {
        obj['class'] = ApiClient.convertToType(data['class'], 'String');
      }
      if (data.hasOwnProperty('rate')) {
        obj['rate'] = ApiClient.convertToType(data['rate'], 'String');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
      }
      if (data.hasOwnProperty('priority_amount')) {
        obj['priority_amount'] = ApiClient.convertToType(data['priority_amount'], 'String');
      }
      if (data.hasOwnProperty('line_amount')) {
        obj['line_amount'] = ApiClient.convertToType(data['line_amount'], 'String');
      }
      if (data.hasOwnProperty('order_product_id')) {
        obj['order_product_id'] = ApiClient.convertToType(data['order_product_id'], 'String');
      }
      if (data.hasOwnProperty('line_item_type')) {
        obj['line_item_type'] = ApiClient.convertToType(data['line_item_type'], 'String');
      }
    }
    return obj;
  }

  /**
   * The unique numeric identifier of the taxes object.
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The unique numeric identifier of the order to which the tax was applied. NOTE: Not included if the store was using the automatic tax feature.
   * @member {Number} order_id
   */
  exports.prototype['order_id'] = undefined;
  /**
   * The unique numeric identifier of the order address object associated with the order. NOTE: Not included if the store was using the automatic tax feature.
   * @member {Number} order_address_id
   */
  exports.prototype['order_address_id'] = undefined;
  /**
   * The unique numeric identifier of the tax rate.
   * @member {Number} tax_rate_id
   */
  exports.prototype['tax_rate_id'] = undefined;
  /**
   * The unique numeric identifier of the tax class object. NOTE: Will be 0 if automatic tax was enabled, or if the default tax class was used.
   * @member {Number} tax_class_id
   */
  exports.prototype['tax_class_id'] = undefined;
  /**
   * The name of the tax class object.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The name of the type of tax that was applied. NOTE: will be “Automatic Tax” if automatic tax was enabled.
   * @member {String} class
   */
  exports.prototype['class'] = undefined;
  /**
   * The tax rate.  The priority order in which the tax is applied (Float, Float-As-String, Integer)
   * @member {String} rate
   */
  exports.prototype['rate'] = undefined;
  /**
   * The order in which the tax is applied
   * @member {Number} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * The amount of tax calculated on the order.   (Float, Float-As-String, Integer)
   * @member {String} priority_amount
   */
  exports.prototype['priority_amount'] = undefined;
  /**
   * (Float, Float-As-String, Integer)
   * @member {String} line_amount
   */
  exports.prototype['line_amount'] = undefined;
  /**
   * If the `line_item_type` is `item` or `handling` then this field will be the order product id. Otherwise the field will return as null.
   * @member {String} order_product_id
   */
  exports.prototype['order_product_id'] = undefined;
  /**
   * Type of tax on item
   * @member {String} line_item_type
   */
  exports.prototype['line_item_type'] = undefined;



  return exports;
}));


