/**
 * Orders APIs
 * Orders APIs integrate with point-of-sale, shipping, distribution, and inventory-management systems.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OrdersApIs) {
      root.OrdersApIs = {};
    }
    root.OrdersApIs.OrderProductsResource = factory(root.OrdersApIs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OrderProductsResource model module.
   * @module Model/OrderProductsResource
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderProductsResource</code>.
   * @alias module:Model/OrderProductsResource
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>OrderProductsResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/OrderProductsResource} obj Optional instance to populate.
   * @return {module:Model/OrderProductsResource} The populated <code>OrderProductsResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('resource')) {
        obj['resource'] = ApiClient.convertToType(data['resource'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * 
   * @member {String} resource
   */
  exports.prototype['resource'] = undefined;



  return exports;
}));


