/**
 * BigCommerce Widgets API
 * Widgets API allows developers to inject content into a BigCommerce theme.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/Placement'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Placement'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceWidgetsApi) {
      root.BigCommerceWidgetsApi = {};
    }
    root.BigCommerceWidgetsApi.PlacementResponse = factory(root.BigCommerceWidgetsApi.ApiClient, root.BigCommerceWidgetsApi.Placement);
  }
}(this, function(ApiClient, Placement) {
  'use strict';




  /**
   * The PlacementResponse model module.
   * @module Model/PlacementResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PlacementResponse</code>.
   * 
   * @alias module:Model/PlacementResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PlacementResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/PlacementResponse} obj Optional instance to populate.
   * @return {module:Model/PlacementResponse} The populated <code>PlacementResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = Placement.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = ApiClient.convertToType(data['meta'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {module:Model/Placement} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {Object} meta
   */
  exports.prototype['meta'] = undefined;



  return exports;
}));


