/**
 * BigCommerce API
 * A Swagger Document for the BigCommmerce v3 Price Lists API.
 *
 * OpenAPI spec version: 3.0.0b
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/PriceRecordBatchErrorSet'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PriceRecordBatchErrorSet'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceApi) {
      root.BigCommerceApi = {};
    }
    root.BigCommerceApi.PriceRecordBatchErrorResponse = factory(root.BigCommerceApi.ApiClient, root.BigCommerceApi.PriceRecordBatchErrorSet);
  }
}(this, function(ApiClient, PriceRecordBatchErrorSet) {
  'use strict';




  /**
   * The PriceRecordBatchErrorResponse model module.
   * @module Model/PriceRecordBatchErrorResponse
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>PriceRecordBatchErrorResponse</code>.
   * Errors during batch usage for the BigCommerce API. 
   * @alias module:Model/PriceRecordBatchErrorResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PriceRecordBatchErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/PriceRecordBatchErrorResponse} obj Optional instance to populate.
   * @return {module:Model/PriceRecordBatchErrorResponse} The populated <code>PriceRecordBatchErrorResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('batch_errors')) {
        obj['batch_errors'] = ApiClient.convertToType(data['batch_errors'], [PriceRecordBatchErrorSet]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:Model/PriceRecordBatchErrorSet>} batch_errors
   */
  exports.prototype['batch_errors'] = undefined;



  return exports;
}));


