/**
 * BigCommerce API
 * A Swagger Document for the BigCommmerce v3 Catalog API.
 *
 * OpenAPI spec version: 3.0.0b
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/CustomUrlProduct'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomUrlProduct'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceApi) {
      root.BigCommerceApi = {};
    }
    root.BigCommerceApi.ProductBase = factory(root.BigCommerceApi.ApiClient, root.BigCommerceApi.CustomUrlProduct);
  }
}(this, function(ApiClient, CustomUrlProduct) {
  'use strict';




  /**
   * The ProductBase model module.
   * @module Model/ProductBase
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>ProductBase</code>.
   * Common Product properties. 
   * @alias module:Model/ProductBase
   * @class
   */
  var exports = function() {
    var _this = this;























































  };

  /**
   * Constructs a <code>ProductBase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/ProductBase} obj Optional instance to populate.
   * @return {module:Model/ProductBase} The populated <code>ProductBase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('weight')) {
        obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
      }
      if (data.hasOwnProperty('width')) {
        obj['width'] = ApiClient.convertToType(data['width'], 'Number');
      }
      if (data.hasOwnProperty('depth')) {
        obj['depth'] = ApiClient.convertToType(data['depth'], 'Number');
      }
      if (data.hasOwnProperty('height')) {
        obj['height'] = ApiClient.convertToType(data['height'], 'Number');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('cost_price')) {
        obj['cost_price'] = ApiClient.convertToType(data['cost_price'], 'Number');
      }
      if (data.hasOwnProperty('retail_price')) {
        obj['retail_price'] = ApiClient.convertToType(data['retail_price'], 'Number');
      }
      if (data.hasOwnProperty('sale_price')) {
        obj['sale_price'] = ApiClient.convertToType(data['sale_price'], 'Number');
      }
      if (data.hasOwnProperty('tax_class_id')) {
        obj['tax_class_id'] = ApiClient.convertToType(data['tax_class_id'], 'Number');
      }
      if (data.hasOwnProperty('product_tax_code')) {
        obj['product_tax_code'] = ApiClient.convertToType(data['product_tax_code'], 'String');
      }
      if (data.hasOwnProperty('categories')) {
        obj['categories'] = ApiClient.convertToType(data['categories'], ['Number']);
      }
      if (data.hasOwnProperty('brand_id')) {
        obj['brand_id'] = ApiClient.convertToType(data['brand_id'], 'Number');
      }
      if (data.hasOwnProperty('inventory_level')) {
        obj['inventory_level'] = ApiClient.convertToType(data['inventory_level'], 'Number');
      }
      if (data.hasOwnProperty('inventory_warning_level')) {
        obj['inventory_warning_level'] = ApiClient.convertToType(data['inventory_warning_level'], 'Number');
      }
      if (data.hasOwnProperty('inventory_tracking')) {
        obj['inventory_tracking'] = ApiClient.convertToType(data['inventory_tracking'], 'String');
      }
      if (data.hasOwnProperty('fixed_cost_shipping_price')) {
        obj['fixed_cost_shipping_price'] = ApiClient.convertToType(data['fixed_cost_shipping_price'], 'Number');
      }
      if (data.hasOwnProperty('is_free_shipping')) {
        obj['is_free_shipping'] = ApiClient.convertToType(data['is_free_shipping'], 'Boolean');
      }
      if (data.hasOwnProperty('is_visible')) {
        obj['is_visible'] = ApiClient.convertToType(data['is_visible'], 'Boolean');
      }
      if (data.hasOwnProperty('is_featured')) {
        obj['is_featured'] = ApiClient.convertToType(data['is_featured'], 'Boolean');
      }
      if (data.hasOwnProperty('related_products')) {
        obj['related_products'] = ApiClient.convertToType(data['related_products'], ['Number']);
      }
      if (data.hasOwnProperty('warranty')) {
        obj['warranty'] = ApiClient.convertToType(data['warranty'], 'String');
      }
      if (data.hasOwnProperty('bin_picking_number')) {
        obj['bin_picking_number'] = ApiClient.convertToType(data['bin_picking_number'], 'String');
      }
      if (data.hasOwnProperty('layout_file')) {
        obj['layout_file'] = ApiClient.convertToType(data['layout_file'], 'String');
      }
      if (data.hasOwnProperty('upc')) {
        obj['upc'] = ApiClient.convertToType(data['upc'], 'String');
      }
      if (data.hasOwnProperty('search_keywords')) {
        obj['search_keywords'] = ApiClient.convertToType(data['search_keywords'], 'String');
      }
      if (data.hasOwnProperty('availability')) {
        obj['availability'] = ApiClient.convertToType(data['availability'], 'String');
      }
      if (data.hasOwnProperty('availability_description')) {
        obj['availability_description'] = ApiClient.convertToType(data['availability_description'], 'String');
      }
      if (data.hasOwnProperty('gift_wrapping_options_type')) {
        obj['gift_wrapping_options_type'] = ApiClient.convertToType(data['gift_wrapping_options_type'], 'String');
      }
      if (data.hasOwnProperty('gift_wrapping_options_list')) {
        obj['gift_wrapping_options_list'] = ApiClient.convertToType(data['gift_wrapping_options_list'], ['Number']);
      }
      if (data.hasOwnProperty('sort_order')) {
        obj['sort_order'] = ApiClient.convertToType(data['sort_order'], 'Number');
      }
      if (data.hasOwnProperty('condition')) {
        obj['condition'] = ApiClient.convertToType(data['condition'], 'String');
      }
      if (data.hasOwnProperty('is_condition_shown')) {
        obj['is_condition_shown'] = ApiClient.convertToType(data['is_condition_shown'], 'Boolean');
      }
      if (data.hasOwnProperty('order_quantity_minimum')) {
        obj['order_quantity_minimum'] = ApiClient.convertToType(data['order_quantity_minimum'], 'Number');
      }
      if (data.hasOwnProperty('order_quantity_maximum')) {
        obj['order_quantity_maximum'] = ApiClient.convertToType(data['order_quantity_maximum'], 'Number');
      }
      if (data.hasOwnProperty('page_title')) {
        obj['page_title'] = ApiClient.convertToType(data['page_title'], 'String');
      }
      if (data.hasOwnProperty('meta_keywords')) {
        obj['meta_keywords'] = ApiClient.convertToType(data['meta_keywords'], ['String']);
      }
      if (data.hasOwnProperty('meta_description')) {
        obj['meta_description'] = ApiClient.convertToType(data['meta_description'], 'String');
      }
      if (data.hasOwnProperty('view_count')) {
        obj['view_count'] = ApiClient.convertToType(data['view_count'], 'Number');
      }
      if (data.hasOwnProperty('preorder_release_date')) {
        obj['preorder_release_date'] = ApiClient.convertToType(data['preorder_release_date'], 'Date');
      }
      if (data.hasOwnProperty('preorder_message')) {
        obj['preorder_message'] = ApiClient.convertToType(data['preorder_message'], 'String');
      }
      if (data.hasOwnProperty('is_preorder_only')) {
        obj['is_preorder_only'] = ApiClient.convertToType(data['is_preorder_only'], 'Boolean');
      }
      if (data.hasOwnProperty('is_price_hidden')) {
        obj['is_price_hidden'] = ApiClient.convertToType(data['is_price_hidden'], 'Boolean');
      }
      if (data.hasOwnProperty('price_hidden_label')) {
        obj['price_hidden_label'] = ApiClient.convertToType(data['price_hidden_label'], 'String');
      }
      if (data.hasOwnProperty('custom_url')) {
        obj['custom_url'] = CustomUrlProduct.constructFromObject(data['custom_url']);
      }
      if (data.hasOwnProperty('open_graph_type')) {
        obj['open_graph_type'] = ApiClient.convertToType(data['open_graph_type'], 'String');
      }
      if (data.hasOwnProperty('open_graph_title')) {
        obj['open_graph_title'] = ApiClient.convertToType(data['open_graph_title'], 'String');
      }
      if (data.hasOwnProperty('open_graph_description')) {
        obj['open_graph_description'] = ApiClient.convertToType(data['open_graph_description'], 'String');
      }
      if (data.hasOwnProperty('open_graph_use_meta_description')) {
        obj['open_graph_use_meta_description'] = ApiClient.convertToType(data['open_graph_use_meta_description'], 'Boolean');
      }
      if (data.hasOwnProperty('open_graph_use_product_name')) {
        obj['open_graph_use_product_name'] = ApiClient.convertToType(data['open_graph_use_product_name'], 'Boolean');
      }
      if (data.hasOwnProperty('open_graph_use_image')) {
        obj['open_graph_use_image'] = ApiClient.convertToType(data['open_graph_use_image'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * The product name. 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The product type. One of: `physical` - a physical stock unit, `digital` - a digital download. 
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * User defined product code/stock keeping unit (SKU). 
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * The product description, which can include HTML formatting. 
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * Weight of the product, which can be used when calculating shipping costs. 
   * @member {Number} weight
   */
  exports.prototype['weight'] = undefined;
  /**
   * Width of the product, which can be used when calculating shipping costs. 
   * @member {Number} width
   */
  exports.prototype['width'] = undefined;
  /**
   * Depth of the product, which can be used when calculating shipping costs. 
   * @member {Number} depth
   */
  exports.prototype['depth'] = undefined;
  /**
   * Height of the product, which can be used when calculating shipping costs. 
   * @member {Number} height
   */
  exports.prototype['height'] = undefined;
  /**
   * The price of the product. The price should include or exclude tax, based on the store settings. 
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * The cost price of the product. Stored for reference only; it is not used or displayed anywhere on the store. 
   * @member {Number} cost_price
   */
  exports.prototype['cost_price'] = undefined;
  /**
   * The retail cost of the product. If entered, the retail cost price will be shown on the product page. 
   * @member {Number} retail_price
   */
  exports.prototype['retail_price'] = undefined;
  /**
   * If entered, the sale price will be used instead of value in the price field when calculating the product's cost. 
   * @member {Number} sale_price
   */
  exports.prototype['sale_price'] = undefined;
  /**
   * The ID of the tax class applied to the product. (NOTE: Value ignored if automatic tax is enabled.) 
   * @member {Number} tax_class_id
   */
  exports.prototype['tax_class_id'] = undefined;
  /**
   * Accepts AvaTax System Tax Codes, which identify products and services that fall into special sales-tax categories. By using these codes, merchants who subscribe to BigCommerce's Avalara Premium integration can calculate sales taxes more accurately. Stores without Avalara Premium will ignore the code when calculating sales tax. Do not pass more than one code. The codes are case-sensitive. For details, please see Avalara's documentation. 
   * @member {String} product_tax_code
   */
  exports.prototype['product_tax_code'] = undefined;
  /**
   * An array of IDs for the categories to which this product belongs. When updating a product, if an array of categories is supplied, all product categories will be overwritten. Does not accept more than 1,000 ID values. 
   * @member {Array.<Number>} categories
   */
  exports.prototype['categories'] = undefined;
  /**
   * The ID associated with the product's brand. 
   * @member {Number} brand_id
   */
  exports.prototype['brand_id'] = undefined;
  /**
   * Current inventory level of the product. Simple inventory tracking must be enabled (See the `inventory_tracking` field) for this to take any effect. 
   * @member {Number} inventory_level
   */
  exports.prototype['inventory_level'] = undefined;
  /**
   * Inventory warning level for the product. When the product's inventory level drops below the warning level, the store owner will be informed. Simple inventory tracking must be enabled (see the `inventory_tracking` field) for this to take any effect. 
   * @member {Number} inventory_warning_level
   */
  exports.prototype['inventory_warning_level'] = undefined;
  /**
   * The type of inventory tracking for the product. Values are: `none` - inventory levels will not be tracked; `product` - inventory levels will be tracked using the `inventory_level` and `inventory_warning_level` fields; `variant` - inventory levels will be tracked based on variants, which maintain their own warning levels and inventory levels. 
   * @member {String} inventory_tracking
   */
  exports.prototype['inventory_tracking'] = undefined;
  /**
   * A fixed shipping cost for the product. If defined, this value will be used during checkout instead of normal shipping-cost calculation. 
   * @member {Number} fixed_cost_shipping_price
   */
  exports.prototype['fixed_cost_shipping_price'] = undefined;
  /**
   * Flag used to indicate whether the product has free shipping. If `true`, the shipping cost for the product will be zero. 
   * @member {Boolean} is_free_shipping
   */
  exports.prototype['is_free_shipping'] = undefined;
  /**
   * Flag to determine whether the product should be displayed to customers browsing the store. If `true`, the product will be displayed. If `false`, the product will be hidden from view. 
   * @member {Boolean} is_visible
   */
  exports.prototype['is_visible'] = undefined;
  /**
   * Flag to determine whether the product should be included in the `featured products` panel when viewing the store. 
   * @member {Boolean} is_featured
   */
  exports.prototype['is_featured'] = undefined;
  /**
   * An array of IDs for the related products. 
   * @member {Array.<Number>} related_products
   */
  exports.prototype['related_products'] = undefined;
  /**
   * Warranty information displayed on the product page. Can include HTML formatting. 
   * @member {String} warranty
   */
  exports.prototype['warranty'] = undefined;
  /**
   * The BIN picking number for the product. 
   * @member {String} bin_picking_number
   */
  exports.prototype['bin_picking_number'] = undefined;
  /**
   * The layout template file used to render this product. 
   * @member {String} layout_file
   */
  exports.prototype['layout_file'] = undefined;
  /**
   * The product UPC code, which is used in feeds for shopping comparison sites and external channel integrations. 
   * @member {String} upc
   */
  exports.prototype['upc'] = undefined;
  /**
   * A comma-separated list of keywords that can be used to locate the product when searching the store. 
   * @member {String} search_keywords
   */
  exports.prototype['search_keywords'] = undefined;
  /**
   * Availability of the product. Availability options are: `available` - the product can be purchased on the storefront; `disabled` - the product is listed in the storefront, but cannot be purchased; `preorder` - the product is listed for pre-orders. 
   * @member {String} availability
   */
  exports.prototype['availability'] = undefined;
  /**
   * Availability text displayed on the checkout page, under the product title. Tells the customer how long it will normally take to ship this product, such as: 'Usually ships in 24 hours.' 
   * @member {String} availability_description
   */
  exports.prototype['availability_description'] = undefined;
  /**
   * Type of gift-wrapping options. Values: `any` - allow any gift-wrapping options in the store; `none` - disallow gift-wrapping on the product; `list` – provide a list of IDs in the `gift_wrapping_options_list` field. 
   * @member {String} gift_wrapping_options_type
   */
  exports.prototype['gift_wrapping_options_type'] = undefined;
  /**
   * A list of gift-wrapping option IDs. 
   * @member {Array.<Number>} gift_wrapping_options_list
   */
  exports.prototype['gift_wrapping_options_list'] = undefined;
  /**
   * Priority to give this product when included in product lists on category pages and in search results. Lower integers will place the product closer to the top of the results. 
   * @member {Number} sort_order
   */
  exports.prototype['sort_order'] = undefined;
  /**
   * The product condition. Will be shown on the product page if the `is_condition_shown` field's value is `true`. Possible values: `New`, `Used`, `Refurbished`. 
   * @member {String} condition
   */
  exports.prototype['condition'] = undefined;
  /**
   * Flag used to determine whether the product condition is shown to the customer on the product page. 
   * @member {Boolean} is_condition_shown
   */
  exports.prototype['is_condition_shown'] = undefined;
  /**
   * The minimum quantity an order must contain, to be eligible to purchase this product. 
   * @member {Number} order_quantity_minimum
   */
  exports.prototype['order_quantity_minimum'] = undefined;
  /**
   * The maximum quantity an order can contain when purchasing the product. 
   * @member {Number} order_quantity_maximum
   */
  exports.prototype['order_quantity_maximum'] = undefined;
  /**
   * Custom title for the product page. If not defined, the product name will be used as the meta title. 
   * @member {String} page_title
   */
  exports.prototype['page_title'] = undefined;
  /**
   * Custom meta keywords for the product page. If not defined, the store's default keywords will be used. 
   * @member {Array.<String>} meta_keywords
   */
  exports.prototype['meta_keywords'] = undefined;
  /**
   * Custom meta description for the product page. If not defined, the store's default meta description will be used. 
   * @member {String} meta_description
   */
  exports.prototype['meta_description'] = undefined;
  /**
   * The number of times the product has been viewed. 
   * @member {Number} view_count
   */
  exports.prototype['view_count'] = undefined;
  /**
   * Pre-order release date. See the `availability` field for details on setting a product's availability to accept pre-orders. 
   * @member {Date} preorder_release_date
   */
  exports.prototype['preorder_release_date'] = undefined;
  /**
   * Custom expected-date message to display on the product page. If undefined, the message defaults to the storewide setting. Can contain the `%%DATE%%` placeholder, which will be substituted for the release date. 
   * @member {String} preorder_message
   */
  exports.prototype['preorder_message'] = undefined;
  /**
   * If set to `false`, the product will not change its availability from `preorder` to `available` on the release date. Otherwise, on the release date the product's availability/status will change to `available`. 
   * @member {Boolean} is_preorder_only
   */
  exports.prototype['is_preorder_only'] = undefined;
  /**
   * False by default, indicating that this product's price should be shown on the product page. If set to `true`, the price is hidden. (NOTE: To successfully set `is_price_hidden` to `true`, the `availability` value must be `disabled`.) 
   * @member {Boolean} is_price_hidden
   */
  exports.prototype['is_price_hidden'] = undefined;
  /**
   * By default, an empty string. If `is_price_hidden` is `true`, the value of `price_hidden_label` is displayed instead of the price. (NOTE: To successfully set a non-empty string value with `is_price_hidden` set to `true`, the `availability` value must be `disabled`.) 
   * @member {String} price_hidden_label
   */
  exports.prototype['price_hidden_label'] = undefined;
  /**
   * @member {module:Model/CustomUrlProduct} custom_url
   */
  exports.prototype['custom_url'] = undefined;
  /**
   * Type of product, defaults to `product`. 
   * @member {String} open_graph_type
   */
  exports.prototype['open_graph_type'] = undefined;
  /**
   * Title of the product, if not specified the product name will be used instead. 
   * @member {String} open_graph_title
   */
  exports.prototype['open_graph_title'] = undefined;
  /**
   * Description to use for the product, if not specified then the meta_description will be used instead. 
   * @member {String} open_graph_description
   */
  exports.prototype['open_graph_description'] = undefined;
  /**
   * Flag to determine if product description or open graph description is used. 
   * @member {Boolean} open_graph_use_meta_description
   */
  exports.prototype['open_graph_use_meta_description'] = undefined;
  /**
   * Flag to determine if product name or open graph name is used. 
   * @member {Boolean} open_graph_use_product_name
   */
  exports.prototype['open_graph_use_product_name'] = undefined;
  /**
   * Flag to determine if product image or open graph image is used. 
   * @member {Boolean} open_graph_use_image
   */
  exports.prototype['open_graph_use_image'] = undefined;



  return exports;
}));


