/**
 * Sites & Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/CollectionMeta', 'Model/Route'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CollectionMeta'), require('./Route'));
  } else {
    // Browser globals (root is window)
    if (!root.SitesRoutes) {
      root.SitesRoutes = {};
    }
    root.SitesRoutes.RouteCollectionResponse = factory(root.SitesRoutes.ApiClient, root.SitesRoutes.CollectionMeta, root.SitesRoutes.Route);
  }
}(this, function(ApiClient, CollectionMeta, Route) {
  'use strict';




  /**
   * The RouteCollectionResponse model module.
   * @module Model/RouteCollectionResponse
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>RouteCollectionResponse</code>.
   * @alias module:Model/RouteCollectionResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>RouteCollectionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/RouteCollectionResponse} obj Optional instance to populate.
   * @return {module:Model/RouteCollectionResponse} The populated <code>RouteCollectionResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [Route]);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = CollectionMeta.constructFromObject(data['meta']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:Model/Route>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:Model/CollectionMeta} meta
   */
  exports.prototype['meta'] = undefined;



  return exports;
}));


