/**
 * BigCommerce API
 * A Swagger Document for the BigCommmerce v3 Scripts API.
 *
 * OpenAPI spec version: 3.0.0b
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/Script'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Script'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceApi) {
      root.BigCommerceApi = {};
    }
    root.BigCommerceApi.ScriptResponse = factory(root.BigCommerceApi.ApiClient, root.BigCommerceApi.Script);
  }
}(this, function(ApiClient, Script) {
  'use strict';




  /**
   * The ScriptResponse model module.
   * @module Model/ScriptResponse
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>ScriptResponse</code>.
   * @alias module:Model/ScriptResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ScriptResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/ScriptResponse} obj Optional instance to populate.
   * @return {module:Model/ScriptResponse} The populated <code>ScriptResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = Script.constructFromObject(data['data']);
      }
    }
    return obj;
  }

  /**
   * @member {module:Model/Script} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


