/**
 * Sites & Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/Route'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Route'));
  } else {
    // Browser globals (root is window)
    if (!root.SitesRoutes) {
      root.SitesRoutes = {};
    }
    root.SitesRoutes.Site = factory(root.SitesRoutes.ApiClient, root.SitesRoutes.Route);
  }
}(this, function(ApiClient, Route) {
  'use strict';




  /**
   * The Site model module.
   * @module Model/Site
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Site</code>.
   * @alias module:Model/Site
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Site</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/Site} obj Optional instance to populate.
   * @return {module:Model/Site} The populated <code>Site</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('channel_id')) {
        obj['channel_id'] = ApiClient.convertToType(data['channel_id'], 'Number');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
      if (data.hasOwnProperty('routes')) {
        obj['routes'] = ApiClient.convertToType(data['routes'], [Route]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The Fully Qualified URL (including host and scheme) where this site is hosted. All URLs generated for this site will be appended to this.
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * The channel this site is attached to. Each site belongs to a single channel, and each channel can have either zero or one sites.
   * @member {Number} channel_id
   */
  exports.prototype['channel_id'] = undefined;
  /**
   * When was this site created? RFC 3339
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * When was this site defintion last updated? RFC 3339
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * (optional - if included) collection of routes defined for this site. Limited to 200 routes side loaded (query routes direction via `/routes` for bulk)
   * @member {Array.<module:Model/Route>} routes
   */
  exports.prototype['routes'] = undefined;



  return exports;
}));


