/**
 * BigCommerce API
 * A Swagger Document for the BigCommmerce v3 Order Transactions API.
 *
 * OpenAPI spec version: 3.0.0b
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceApi) {
      root.BigCommerceApi = {};
    }
    root.BigCommerceApi.StoreCredit = factory(root.BigCommerceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StoreCredit model module.
   * @module Model/StoreCredit
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>StoreCredit</code>.
   * A store credit model. 
   * @alias module:Model/StoreCredit
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>StoreCredit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/StoreCredit} obj Optional instance to populate.
   * @return {module:Model/StoreCredit} The populated <code>StoreCredit</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('remaining_balance')) {
        obj['remaining_balance'] = ApiClient.convertToType(data['remaining_balance'], 'String');
      }
    }
    return obj;
  }

  /**
   * Remaining balance of shopper's store credit. 
   * @member {String} remaining_balance
   */
  exports.prototype['remaining_balance'] = undefined;



  return exports;
}));


