/**
 * BigCommerce API
 * A Swagger Document for the BigCommmerce v3 Order Transactions API.
 *
 * OpenAPI spec version: 3.0.0b
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/Transaction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Transaction'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceApi) {
      root.BigCommerceApi = {};
    }
    root.BigCommerceApi.TransactionResponse = factory(root.BigCommerceApi.ApiClient, root.BigCommerceApi.Transaction);
  }
}(this, function(ApiClient, Transaction) {
  'use strict';




  /**
   * The TransactionResponse model module.
   * @module Model/TransactionResponse
   * @version 3.0.0b
   */

  /**
   * Constructs a new <code>TransactionResponse</code>.
   * Response payload for the BigCommerce Order Transactions API single transaction. 
   * @alias module:Model/TransactionResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TransactionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/TransactionResponse} obj Optional instance to populate.
   * @return {module:Model/TransactionResponse} The populated <code>TransactionResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = Transaction.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = ApiClient.convertToType(data['meta'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {module:Model/Transaction} data
   */
  exports.prototype['data'] = undefined;
  /**
   * May be used in the future
   * @member {Object} meta
   */
  exports.prototype['meta'] = undefined;



  return exports;
}));


