/**
 * BigCommerce Widgets API
 * Widgets API allows developers to inject content into a BigCommerce theme.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceWidgetsApi) {
      root.BigCommerceWidgetsApi = {};
    }
    root.BigCommerceWidgetsApi.WidgetTemplateRequest = factory(root.BigCommerceWidgetsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WidgetTemplateRequest model module.
   * @module Model/WidgetTemplateRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WidgetTemplateRequest</code>.
   * @alias module:Model/WidgetTemplateRequest
   * @class
   * @param name {String} User friendly name.
   * @param template {String} Handlebars HTML content. Also has access to Stencil Paper helpers.
   */
  var exports = function(name, template) {
    var _this = this;

    _this['name'] = name;

    _this['template'] = template;
  };

  /**
   * Constructs a <code>WidgetTemplateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/WidgetTemplateRequest} obj Optional instance to populate.
   * @return {module:Model/WidgetTemplateRequest} The populated <code>WidgetTemplateRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('schema')) {
        obj['schema'] = ApiClient.convertToType(data['schema'], Object);
      }
      if (data.hasOwnProperty('template')) {
        obj['template'] = ApiClient.convertToType(data['template'], 'String');
      }
    }
    return obj;
  }

  /**
   * User friendly name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The JSON schema of data for this template. Used to validate a configuration.
   * @member {Object} schema
   */
  exports.prototype['schema'] = undefined;
  /**
   * Handlebars HTML content. Also has access to Stencil Paper helpers.
   * @member {String} template
   */
  exports.prototype['template'] = undefined;



  return exports;
}));


