/**
 * BigCommerce Widgets API
 * Widgets API allows developers to inject content into a BigCommerce theme.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceWidgetsApi) {
      root.BigCommerceWidgetsApi = {};
    }
    root.BigCommerceWidgetsApi.WidgetRequest = factory(root.BigCommerceWidgetsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WidgetRequest model module.
   * @module Model/WidgetRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WidgetRequest</code>.
   * @alias module:Model/WidgetRequest
   * @class
   * @param name {String} User friendly name.
   * @param widgetTemplateUuid {String} The widget template UUID.
   */
  var exports = function(name, widgetTemplateUuid) {
    var _this = this;

    _this['name'] = name;


    _this['widget_template_uuid'] = widgetTemplateUuid;
  };

  /**
   * Constructs a <code>WidgetRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/WidgetRequest} obj Optional instance to populate.
   * @return {module:Model/WidgetRequest} The populated <code>WidgetRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('widget_configuration')) {
        obj['widget_configuration'] = ApiClient.convertToType(data['widget_configuration'], Object);
      }
      if (data.hasOwnProperty('widget_template_uuid')) {
        obj['widget_template_uuid'] = ApiClient.convertToType(data['widget_template_uuid'], 'String');
      }
    }
    return obj;
  }

  /**
   * User friendly name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The user-friendly description.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * The JSON data that populates the template.
   * @member {Object} widget_configuration
   */
  exports.prototype['widget_configuration'] = undefined;
  /**
   * The widget template UUID.
   * @member {String} widget_template_uuid
   */
  exports.prototype['widget_template_uuid'] = undefined;



  return exports;
}));


