/**
 * BigCommerce Widgets API
 * Widgets API allows developers to inject content into a BigCommerce theme.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/WidgetTemplate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WidgetTemplate'));
  } else {
    // Browser globals (root is window)
    if (!root.BigCommerceWidgetsApi) {
      root.BigCommerceWidgetsApi = {};
    }
    root.BigCommerceWidgetsApi.Widget = factory(root.BigCommerceWidgetsApi.ApiClient, root.BigCommerceWidgetsApi.WidgetTemplate);
  }
}(this, function(ApiClient, WidgetTemplate) {
  'use strict';




  /**
   * The Widget model module.
   * @module Model/Widget
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Widget</code>.
   * @alias module:Model/Widget
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>Widget</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/Widget} obj Optional instance to populate.
   * @return {module:Model/Widget} The populated <code>Widget</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('widget_configuration')) {
        obj['widget_configuration'] = ApiClient.convertToType(data['widget_configuration'], Object);
      }
      if (data.hasOwnProperty('widget_template')) {
        obj['widget_template'] = WidgetTemplate.constructFromObject(data['widget_template']);
      }
      if (data.hasOwnProperty('date_created')) {
        obj['date_created'] = ApiClient.convertToType(data['date_created'], 'String');
      }
      if (data.hasOwnProperty('date_modified')) {
        obj['date_modified'] = ApiClient.convertToType(data['date_modified'], 'String');
      }
    }
    return obj;
  }

  /**
   * The primary identifier.
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * The user-friendly name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The user-friendly description.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * The JSON data that populates the template.
   * @member {Object} widget_configuration
   */
  exports.prototype['widget_configuration'] = undefined;
  /**
   * @member {module:Model/WidgetTemplate} widget_template
   */
  exports.prototype['widget_template'] = undefined;
  /**
   * The date on which this object was initially created.
   * @member {String} date_created
   */
  exports.prototype['date_created'] = undefined;
  /**
   * The date on which this object was last updated.
   * @member {String} date_modified
   */
  exports.prototype['date_modified'] = undefined;



  return exports;
}));


