/**
 * Wishlist API
 * The Wishlist API allows a developer to create and manage customer Wishlists.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/CollectionMeta', 'Model/Wishlist'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CollectionMeta'), require('./Wishlist'));
  } else {
    // Browser globals (root is window)
    if (!root.WishlistApi) {
      root.WishlistApi = {};
    }
    root.WishlistApi.WishlistCollectionResponse = factory(root.WishlistApi.ApiClient, root.WishlistApi.CollectionMeta, root.WishlistApi.Wishlist);
  }
}(this, function(ApiClient, CollectionMeta, Wishlist) {
  'use strict';




  /**
   * The WishlistCollectionResponse model module.
   * @module Model/WishlistCollectionResponse
   * @version 1.0
   */

  /**
   * Constructs a new <code>WishlistCollectionResponse</code>.
   * @alias module:Model/WishlistCollectionResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>WishlistCollectionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/WishlistCollectionResponse} obj Optional instance to populate.
   * @return {module:Model/WishlistCollectionResponse} The populated <code>WishlistCollectionResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [Wishlist]);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = CollectionMeta.constructFromObject(data['meta']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:Model/Wishlist>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:Model/CollectionMeta} meta
   */
  exports.prototype['meta'] = undefined;



  return exports;
}));


