/**
 * Wishlist API
 * The Wishlist API allows a developer to create and manage customer Wishlists.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'Model/WishlistItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WishlistItem'));
  } else {
    // Browser globals (root is window)
    if (!root.WishlistApi) {
      root.WishlistApi = {};
    }
    root.WishlistApi.WishlistAddItemsRequest = factory(root.WishlistApi.ApiClient, root.WishlistApi.WishlistItem);
  }
}(this, function(ApiClient, WishlistItem) {
  'use strict';




  /**
   * The WishlistAddItemsRequest model module.
   * @module Model/WishlistAddItemsRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>WishlistAddItemsRequest</code>.
   * @alias module:Model/WishlistAddItemsRequest
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>WishlistAddItemsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Model/WishlistAddItemsRequest} obj Optional instance to populate.
   * @return {module:Model/WishlistAddItemsRequest} The populated <code>WishlistAddItemsRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [WishlistItem]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:Model/WishlistItem>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


