/*
 * Carts
 * ### Cart Allows for a cart to be created using BigCommerce cart logic. The existing BigCommerce front end cart can be bypassed.  Notes: - A **cart** `id` is the same as a **checkout** `id`. - A cart can be created by adding an existing **catalog item** or a **custom item**. - Carts are valid for 30 days from the last modification. This can include creating the cart or editing the cart. - Redirect URLs can be generated only from carts created using the Server to Server Cart API. To restore a cart that was created on the storefront, either by a shopper or the Storefront Cart API, first recreate the cart using the Server to Server Cart API.
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.21
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'), require('../../src/BCApiClient'), require('../config'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Carts);
  }
}(this, function(expect, Carts, BCApiClient, config) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Carts.CartItemsApi(new BCApiClient(config));
  });

  describe('(package)', function() {
    describe('CartItemsApi', function() {
      describe('addCartLineItem', function() {
        it('should call addCartLineItem successfully', async function() {
          // const addCartLineItemResponse = await instance.addCartLineItem();
          // expect(addCartLineItemResponse.ok).to.be(true);
          // expect(addCartLineItemResponse.body.data).to.be.an('array');
        });
      });
      describe('deleteCartLineItem', function() {
        it('should call deleteCartLineItem successfully', async function() {
          // const deleteCartLineItemResponse = await instance.deleteCartLineItem();
          // expect(deleteCartLineItemResponse.ok).to.be(true);
          // expect(deleteCartLineItemResponse.body.data).to.be.an('array');
        });
      });
      describe('updateCartLineItem', function() {
        it('should call updateCartLineItem successfully', async function() {
          // const updateCartLineItemResponse = await instance.updateCartLineItem();
          // expect(updateCartLineItemResponse.ok).to.be(true);
          // expect(updateCartLineItemResponse.body.data).to.be.an('array');
        });
      });
    });
  });

}));
