/**
 * Store Information
 * ### Store Information Reference The Store Information object, and Get Store Information endpoint, manage store profile settings. A Store Information object represents an individual store’s profile and metadata.  ### System Reference The Get a Timestamp endpoint generates a timestamp ping to check the system status.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TimeStampFull1 model module.
* @module model/TimeStampFull1
* @version 2.0
*/
export default class TimeStampFull1 {
    /**
    * Constructs a new <code>TimeStampFull1</code>.
    * Store Time in Unix format.
    * @alias module:model/TimeStampFull1
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TimeStampFull1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TimeStampFull1} obj Optional instance to populate.
    * @return {module:model/TimeStampFull1} The populated <code>TimeStampFull1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeStampFull1();
                        
            
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} time
    */
    'time' = undefined;




}
