/**
 * Wishlist
 * ## Wishlist API    The Wishlist API allows a developer to create and manage customer [Wishlists](https://support.bigcommerce.com/s/article/Wishlists). A Wishlist allows you to see what your customers are interested in and saving on the store. With this information you’ll be able to create targeted campaigns to help merchants grow their business. Customer API OAuth scopes give you access to Wishlists API. See [OAuth Scopes](https://developer.bigcommerce.com/api-docs/getting-started/authentication#authentication_oauth-scopes).
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Pagination model module.
* @module model/Pagination
* @version 3.0
*/
export default class Pagination {
    /**
    * Constructs a new <code>Pagination</code>.
    * Data about the response, including pagination and collection totals.
    * @alias module:model/Pagination
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Pagination</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Pagination} obj Optional instance to populate.
    * @return {module:model/Pagination} The populated <code>Pagination</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pagination();
                        
            
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('per_page')) {
                obj['per_page'] = ApiClient.convertToType(data['per_page'], 'Number');
            }
            if (data.hasOwnProperty('current_page')) {
                obj['current_page'] = ApiClient.convertToType(data['current_page'], 'Number');
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Total number of items in the result set.
    * @member {Number} total
    */
    'total' = undefined;
    /**
    * Total number of items in the collection response.
    * @member {Number} count
    */
    'count' = undefined;
    /**
    * The amount of items returned in the collection per page, controlled by the limit parameter.
    * @member {Number} per_page
    */
    'per_page' = undefined;
    /**
    * The page you are currently on within the collection.
    * @member {Number} current_page
    */
    'current_page' = undefined;
    /**
    * The total number of pages in the collection.
    * @member {Number} total_pages
    */
    'total_pages' = undefined;




}
