/**
 * Wishlist
 * ## Wishlist API    The Wishlist API allows a developer to create and manage customer [Wishlists](https://support.bigcommerce.com/s/article/Wishlists). A Wishlist allows you to see what your customers are interested in and saving on the store. With this information you’ll be able to create targeted campaigns to help merchants grow their business. Customer API OAuth scopes give you access to Wishlists API. See [OAuth Scopes](https://developer.bigcommerce.com/api-docs/getting-started/authentication#authentication_oauth-scopes).
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WishlistItem from './WishlistItem';

/**
* The WishlistPut1 model module.
* @module model/WishlistPut1
* @version 3.0
*/
export default class WishlistPut1 {
    /**
    * Constructs a new <code>WishlistPut1</code>.
    * @alias module:model/WishlistPut1
    * @class
    * @param customerId {Number} The customer id.
    */

    constructor(customerId) {
        
        
        this['customer_id'] = customerId;
        
    }

    /**
    * Constructs a <code>WishlistPut1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WishlistPut1} obj Optional instance to populate.
    * @return {module:model/WishlistPut1} The populated <code>WishlistPut1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WishlistPut1();
                        
            
            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'Number');
            }
            if (data.hasOwnProperty('is_public')) {
                obj['is_public'] = ApiClient.convertToType(data['is_public'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [WishlistItem]);
            }
        }
        return obj;
    }

    /**
    * The customer id.
    * @member {Number} customer_id
    */
    'customer_id' = undefined;
    /**
    * Whether the wishlist is available to the public.
    * @member {Boolean} is_public
    */
    'is_public' = undefined;
    /**
    * The title of the wishlist.
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Array of Wishlist items.
    * @member {Array.<module:model/WishlistItem>} items
    */
    'items' = undefined;




}
