/**
 * Widgets
 * Widgets API allows developers to programatically inject content into a BigCommerce theme. To learn how to use Widgets, see our [Widgets Overview](/api-docs/storefront/widgets/widgets-overview).
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AllOfinlineResponse2004Data model module.
* @module model/AllOfinlineResponse2004Data
* @version 3.0
*/
export default class AllOfinlineResponse2004Data {
    /**
    * Constructs a new <code>AllOfinlineResponse2004Data</code>.
    * @alias module:model/AllOfinlineResponse2004Data
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AllOfinlineResponse2004Data</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AllOfinlineResponse2004Data} obj Optional instance to populate.
    * @return {module:model/AllOfinlineResponse2004Data} The populated <code>AllOfinlineResponse2004Data</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllOfinlineResponse2004Data();
                        
            
            if (data.hasOwnProperty('entity_id')) {
                obj['entity_id'] = ApiClient.convertToType(data['entity_id'], 'String');
            }
            if (data.hasOwnProperty('sort_order')) {
                obj['sort_order'] = ApiClient.convertToType(data['sort_order'], 'Number');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('widget')) {
                obj['widget'] = ApiClient.convertToType(data['widget'], Object);
            }
        }
        return obj;
    }

    /**
    * The specific instance of a page that you would like to target.
    * @member {String} entity_id
    */
    'entity_id' = undefined;
    /**
    * The sort order to control the position of a content widget in a region.
    * @member {Number} sort_order
    */
    'sort_order' = undefined;
    /**
    * The name of the region in which to insert content widgets.
    * @member {String} region
    */
    'region' = undefined;
    /**
    * Sets the placement as either inactive or active.
    * @member {module:model/AllOfinlineResponse2004Data.StatusEnum} status
    * @default 'inactive'
    */
    'status' = 'inactive';
    /**
    * @member {Object} widget
    */
    'widget' = undefined;



    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
        /**
         * value: "inactive"
         * @const
         */
        "inactive": "inactive",
        /**
         * value: "active"
         * @const
         */
        "active": "active"    };

}
