/**
 * Widgets
 * Widgets API allows developers to programatically inject content into a BigCommerce theme. To learn how to use Widgets, see our [Widgets Overview](/api-docs/storefront/widgets/widgets-overview).
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ThemeRegion model module.
* @module model/ThemeRegion
* @version 3.0
*/
export default class ThemeRegion {
    /**
    * Constructs a new <code>ThemeRegion</code>.
    * @alias module:model/ThemeRegion
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ThemeRegion</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ThemeRegion} obj Optional instance to populate.
    * @return {module:model/ThemeRegion} The populated <code>ThemeRegion</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThemeRegion();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * The region name.
    * @member {String} name
    */
    'name' = undefined;




}
